### ISSUE TITLE
Anchor links not rendered in rich text editor

### ISSUE THREAD

**Issue by atteism** [dest81/wagtailset#3]
I can make anchors in a page and links to them from within the same page. I save the page and it renders correctly.

However, when editing the page again, the anchor link is not showing up in the rich text editor. If I save the page in this state, the anchor link is (of course) gone.

Guessing this has to do with the conversion from database format to rich text editor format, but cannot figure out what is going wrong.

Wagtail version 4.2.2.

Any help is welcome. Thank you!

**Comment by dest81** [comment]
Should be fixed
